### ISSUE TITLE
Test  Android-CPP

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-review-sample#6]
以下为 review android cpp 的测试结果

第三次启动弹出评价提示窗口，窗口中有立即评价，稍后再来，残忍拒绝三个选项。
点击立即评价后在前往评价过程中取消，再打开应用不会提示评价。点稍后评价后，同样再打开应用不会提示评价。

**Comment by hugohuang1111** [comment]
"LaunchLimit": 3,           //prompt after launch 3 times
"DayForReminding": 1,    //prompt after 1 day, so if you select "later",  will prompt after 1 day
"tryPromptWhenInit": true,   //prompt when app launch
"DayLimit": 0,               //promtp after 0 day
"LaunchForReminding": 2,   //prompt after launch 2 times, so if you selected "later", will prompt after launch 2 times
"UserEventLimit": 0  //prompt after 0 times user event

if you set both launch times limit and day limit, must reach launch and day limit, then will prompt user

**Comment by hugohuang1111** [comment]
now, the sample project setting is
"DayForReminding": 1，
"LaunchForReminding": 2

so, will prompt user after 1 day and user launch 2 times again
